### ISSUE TITLE
Cannot freeze CustomForeignKeyField when creating south migration

### ISSUE THREAD

**Issue by mghantous** [jazzband/django-simple-history#129]
I'm using:
Python 2.6.9
Django==1.4.13
South==0.8.1
django-simple-history==1.5.2

When I try to do a ./manage.py schemamigration myapp --auto I get the following error:

 ! Cannot freeze field 'myapp.historicalmymodel.myothermodel_id'
 ! (this field has class simple_history.models.CustomForeignKeyField)

 ! South cannot introspect some fields; this is probably because they are custom
 ! fields. If they worked in 0.6 or below, this is because we have removed the
 ! models parser (it often broke things).
 ! To fix this, read http://south.aeracode.org/wiki/MyFieldsDontWork

I tried following the steps from the South page and added this:
from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^simple_history.models.CustomForeignKeyField"])

That allowed me to create the migration, but then when I actually tried to run it I got the following error:
  File "/Users/mghantous/.virtual_envs/myproject/lib/python2.6/site-packages/django/db/models/fields/related.py", line 110, in resolve_related_class
    field.do_related_class(model, cls)
  File "/Users/mghantous/.virtual_envs/myproject/lib/python2.6/site-packages/simple_history/models.py", line 287, in do_related_class
    instance_type = cls.instance_type
AttributeError: type object 'HistoricalMyModel' has no attribute 'instance_type'

I should also mention MyModel inherits from another model that is Polymorphic. I think that might have something to do with it.

class MyBaseModel(PolymorphicModel)
class MyMode(MyBaseModel)

If I downgrade back to django-simple-history==1.3.0, everything works. I am not sure what is happening. Please look into this. Thanks.
